version: '3.1'

services:

  db:
    image: mysql:8.0.3
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306